In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7215, 1279, 5032, 9141], [7215, 1279, 5032, 7038], [7215, 5036, 5032, 6187], [7999, 8606, 346, 265, 4716], [7999, 8606, 346, 265, 2095], [3120, 7215, 8150, 5032, 3910], [7785, 2, 9653, 265]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7215 1279 5032 9141]
 [   0    0    0    0 7215 1279 5032 7038]
 [   0    0    0    0 7215 5036 5032 6187]
 [   0    0    0 7999 8606  346  265 4716]
 [   0    0    0 7999 8606  346  265 2095]
 [   0    0    0 3120 7215 8150 5032 3910]
 [   0    0    0    0 7785    2 9653  265]]


In [10]:
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517
    0.03067681  0.00053041  0.0339103   0.03103981 -0.01236428]
  [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517
    0.03067681  0.00053041  0.0339103   0.03103981 -0.01236428]
  [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517
    0.03067681  0.00053041  0.0339103   0.03103981 -0.01236428]
  [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517
    0.03067681  0.00053041  0.0339103   0.03103981 -0.01236428]
  [ 0.00149946  0.0014016  -0.04709792 -0.03050131  0.03855516
   -0.01190346 -0.02557614  0.00516742  0.0154694   0.02153781]
  [ 0.00096718 -0.03472223 -0.04316647 -0.0277522  -0.02394832
   -0.00690543 -0.03526675 -0.00865082 -0.04470747 -0.04305378]
  [-0.0151678   0.03301071  0.03334287  0.04593093  0.00571444
   -0.0072329  -0.04165993  0.02695984  0.02605144  0.03987355]
  [ 0.01783407  0.01090772  0.03754975  0.0401888  -0.04955133
   -0.02354832  0.04318914  0.00714868 -0.017379

In [53]:
embedded_docs[0]

NameError: name 'embedded_docs' is not defined

In [17]:
print(model.predict(embedded_docs)[0])

[[-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517  0.03067681
   0.00053041  0.0339103   0.03103981 -0.01236428]
 [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517  0.03067681
   0.00053041  0.0339103   0.03103981 -0.01236428]
 [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517  0.03067681
   0.00053041  0.0339103   0.03103981 -0.01236428]
 [-0.01123615  0.01419326  0.04325887 -0.00965564  0.03875517  0.03067681
   0.00053041  0.0339103   0.03103981 -0.01236428]
 [ 0.00149946  0.0014016  -0.04709792 -0.03050131  0.03855516 -0.01190346
  -0.02557614  0.00516742  0.0154694   0.02153781]
 [ 0.00096718 -0.03472223 -0.04316647 -0.0277522  -0.02394832 -0.00690543
  -0.03526675 -0.00865082 -0.04470747 -0.04305378]
 [-0.0151678   0.03301071  0.03334287  0.04593093  0.00571444 -0.0072329
  -0.04165993  0.02695984  0.02605144  0.03987355]
 [ 0.01783407  0.01090772  0.03754975  0.0401888  -0.04955133 -0.02354832
   0.04318914  0.00714868 -0.01737992 -0.01651631]]


# Get started with word embedding

#### In this tutorial, we will learn how to create a word embedding model.

In [34]:
from numpy import array
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [35]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [36]:
# integer encode the documents
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[2, 39], [9, 4], [14, 30], [18, 4], [48], [40], [12, 30], [11, 9], [12, 4], [47, 13, 39, 37]]


In [45]:
# pad documents to a max length of 4 words
max_length = 5
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 2 39  0  0  0]
 [ 9  4  0  0  0]
 [14 30  0  0  0]
 [18  4  0  0  0]
 [48  0  0  0  0]
 [40  0  0  0  0]
 [12 30  0  0  0]
 [11  9  0  0  0]
 [12  4  0  0  0]
 [47 13 39 37  0]]


In [60]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [61]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [62]:
# summarize the model
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 5, 10)             500       
_________________________________________________________________
flatten_5 (Flatten)          (None, 50)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 51        
Total params: 551
Trainable params: 551
Non-trainable params: 0
_________________________________________________________________
None


In [63]:
# fit the model
model.fit(padded_docs, labels, epochs=100, verbose=0)

In [64]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 89.999998


In [68]:
print(model.predict(padded_docs))

[[0.67163485]
 [0.6212301 ]
 [0.5802775 ]
 [0.6770435 ]
 [0.5732119 ]
 [0.4237716 ]
 [0.4196341 ]
 [0.39547795]
 [0.51820016]
 [0.21948579]]


In [66]:
print(model.predict(padded_docs)[0])

[0.67163485]


### Pre-trained word embedding with Glove

In [ ]:
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1

In [ ]:
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)

In [ ]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

In [ ]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('../glove_data/glove.6B/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

In [ ]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [ ]:
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [ ]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

In [ ]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)

In [ ]:
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))